name:                intcode
version:             0.1.0.0
github:              "githubuser/intcode-monadfail"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/intcode-monadfail#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- listsafe
- microlens-platform
- containers
- data-default

library:
  source-dirs: src

tests:
  intcode-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - intcode
    - tasty
    - tasty-hunit
    - tasty-laws >= 0.3.2
    - split
